Repository xsf/xmpp.org, pull requests merged in 2021-02, with the labels that each got.

#864 DRAFT: [newsletter] Update XEP section
  content/posts/newsletter/2021-02-05.md
Labels: Newsletter :email:

#889 Change to correct windows logo
  content/images/logos/windows.svg
Labels: Website :computer_mouse:

#884 Replace Google's XMPP Interface URL
  content/pages/uses/social.md
Labels: Website :computer_mouse:, bug

#886 Update compliance suites link to 2021 (XEP-0443)
  content/pages/extensions.md
Labels: Website :computer_mouse:

#891 [newsletter] Update 2021-02-05.md
  content/posts/newsletter/2021-02-05.md
Labels: Newsletter :email:

#851 DRAFT: XMPP Newsletter January 2021
  content/images/newsletter/january2021/GajimProfile.png
  content/images/newsletter/january2021/monalproductpagepreview.png
  content/posts/newsletter/2021-02-05.md
Labels: Newsletter :email:

#892 Renew BeagleIM/SiskinIM/StorkIM
  data/clients.json
Labels: Update

#887 Add link to overview of XSF logs
  content/pages/community/chat.md
Labels: Website :computer_mouse:, enhancement

#893 Renew yaxim and Bruno
  data/clients.json
Labels: Update

#895 Newsletter page: Add contribution information
  content/pages/newsletter.md
Labels: Website :computer_mouse:

#897 Add Aparté in clients list
  data/clients.json
Labels: Update

#900 Renew all IgniteRealtime projects
  data/clients.json
  data/libraries.json
  data/servers.json
Labels: Update
