Repository xsf/xmpp.org, pull requests merged in 2021-09, with the labels that each got.

#956 REVIEW: XMPP Newsletter August 2021
  content/images/newsletter/august2021/communique.png
  content/images/newsletter/august2021/gajim-workspaces-preview.png
  content/images/newsletter/august2021/snikket_on_ios.png
  content/images/newsletter/august2021/test.txt
  content/posts/newsletter/2021-09-05.md
Labels: Newsletter :email:

#962 Fixes for the new Hugo based site
  README.md
  config/_default/config.toml
  content/blog/2021-09-05.md
  content/software/clients.md
  content/software/libraries.md
  content/software/servers.md
  themes/xmpp.org/layouts/_default/rss.xml
  themes/xmpp.org/layouts/index.html
  themes/xmpp.org/layouts/partials/footer.html
  themes/xmpp.org/layouts/partials/nav.html
  themes/xmpp.org/layouts/partials/post_meta.html
  themes/xmpp.org/layouts/partials/sidebar_blog.html
Labels: Website :computer_mouse:

#963 Further fixes for the new Hugo based website
  README.md
  content/blog/xmpp-report-1-security-pep-and-microblogging.md
  content/blog/xmpp-report-2.md
  content/blog/xmpp-roundup-3.md
  content/blog/xmpp-roundup-4-new-year-edition.md
  content/blog/xmpp-roundup-5.md
  content/blog/xmpp-roundup-7-brussels-report.md
  content/blog/xmpp-roundup-8.md
  content/blog/xmpp-roundup-9.md
  content/blog/xmpp-roundup.md
  content/images/newsletter/august2021/test.txt
  deploy/xsf.conf
  static/images/newsletter/august2021/communique.png
  static/images/newsletter/august2021/gajim-workspaces-preview.png
  static/images/newsletter/august2021/snikket_on_ios.png
  static/images/newsletter/december2020/testdec2020.jpg
  static/images/newsletter/july2020/testtodelete.png
  static/images/newsletter/september2020/placeholder.txt
  themes/xmpp.org/layouts/partials/footer.html
  themes/xmpp.org/layouts/partials/head.html
  themes/xmpp.org/static/css/style.css
Labels: Website :computer_mouse:

#960 create a central redirect for 'current Compliance Suite'
  content/extensions.md
  deploy/xsf.conf
Labels: Website :computer_mouse:

#968 Update instant-messaging.md
  content/uses/instant-messaging.md
Labels: Website :computer_mouse:

#974 Renew Dino
  data/clients.json
Labels: Update

#973 Renew Profanity
  data/clients.json
Labels: Update

#969 Use subresource integrity on stylesheets
  themes/xmpp.org/assets/css/bootstrap.min.css
  themes/xmpp.org/assets/css/style.css
  themes/xmpp.org/assets/fontawesome/css/all.min.css
  themes/xmpp.org/assets/fonts/font.css
  themes/xmpp.org/layouts/partials/head.html
Labels: Website :computer_mouse:

#961 Extensions: Replace Draft status with Stable
  themes/xmpp.org/layouts/shortcodes/extensions-table.html
  tools/prepare_xep_list.py
Labels: Website :computer_mouse:

#966 Replace 'Draft' stage with 'Stable'
  content/about/standards-process.md
  content/extensions.md
Labels: Website :computer_mouse:

#947 Technology-overview: Fix link to RFC 7622
  content/about/technology-overview.md
Labels: Website :computer_mouse:

#915 Add fiscal host policy
  config/_default/menus.en.toml
  content/community/fiscalhost.md
Labels: Website :computer_mouse:, Board

#978 Fiscal host blog
  content/blog/2021-09-26-xsf-fiscal-host.md
  static/images/fiscalhost_step_one.png
  static/images/fiscalhost_step_two.png
Labels: Website :computer_mouse:, Board
