Repository xsf/xmpp.org, pull requests merged in 2021-04, with the labels that each got.

#910 [newsletter] XEP Updates
  content/posts/newsletter/2021-04-05.md
Labels: Newsletter :email:

#909 Add bylaws to menu under /about/xsf
  content/pages/about/xmpp-standards-foundation.md
Labels: Website :computer_mouse:

#883 Libaries: Expand to tools
  content/pages/software/libraries.md
Labels: Update, Website :computer_mouse:

#912 Add txmmp to libraries.json
  data/clients.json
  data/libraries.json
Labels: Update

#906 EDITORIAL CLOSING: Newsletter March 2021
  content/images/newsletter/march2021/conversations.png
  content/images/newsletter/test123.txt
  content/posts/newsletter/2021-04-05.md
Labels: Newsletter :email:

#916 Update timestamp Monal IM
  data/clients.json
Labels: Update

#917 Add doap URL for Monal IM
  data/clients.json
Labels: Update
