Repository xsf/xmpp.org, pull requests merged in 2021-12, with the labels that each got.

#1026 Add SiskinIM 7.0 and BeagleIM 5.0 releases
  content/blog/2021-12-05.md
Labels: Newsletter :email:

#1030 Add one more article and news
  content/blog/2021-12-05.md
Labels: Newsletter :email:

#1012 REVIEW: XMPP Newsletter November 2021
  content/blog/2021-12-05.md
  static/images/newsletter/november2021/gajim-message-moderation.png
Labels: Newsletter :email:

#1034 Renew all IgniteRealtime projects
  data/clients.json
  data/libraries.json
  data/servers.json
Labels: Update

#1036 update members as per Q4-2021 elections
  data/members.json
Labels: Update

#1038 Update announcement.json
  data/announcement.json
Labels: Update, Website :computer_mouse:
