Repository xsf/xmpp.org, pull requests merged in 2021-11, with the labels that each got.

#999 EDITORIAL CLOSING: XMPP Newsletter October 2021
  content/blog/2021-11-05.md
  static/images/newsletter/october2021/bad_xmpp.png
  static/images/newsletter/october2021/beagle-location.jpg
  static/images/newsletter/october2021/test123.txt
Labels: Newsletter :email:

#1003 Update servers.json
  data/servers.json
Labels: Update

#1002 Update clients.json
  data/clients.json
Labels: Update

#1004 New xmpp client
  data/clients.json
Labels: Update

#1006 Update officehours.md
  content/community/officehours.md
Labels: enhancement, Website :computer_mouse:

#1009 add member jids
  data/members.json
Labels: Update

#1010 update roles per annual board and council election
  data/members.json
Labels: Update

#1013 update board and council section
  content/about/xmpp-standards-foundation.md
Labels: Update, Board

#1016 [newsletter] Add UWPX Release News
  content/blog/2021-12-05.md
Labels: Newsletter :email:

#1018 add bio for Travis
  content/about/xmpp-standards-foundation.md
Labels: Update, Board

#1022 clients: Add DOAP file URL for Kaidan
  data/clients.json
Labels: Update

#1023 fix bifrost donate link
  content/blog/2021-12-05.md
Labels: bug, Website :computer_mouse:

#1025 Renew Prosody
  data/servers.json
Labels: Update
