Repository xsf/xmpp.org, pull requests merged in 2021-06, with the labels that each got.

#919 EDITORIAL CLOSING: Create draft of the XMPP Newsletter May 2021
  content/images/newsletter/may2021/Dino_AVcalls.png
  content/images/newsletter/may2021/gajim_youtube.png
  content/posts/newsletter/2021-06-05.md
Labels: Newsletter :email:

#932 update members as per Q2-2021 elections
  data/members.json
Labels: Update

#934 Change link to correct site of CommTeam
  content/pages/newsletter.md
Labels: Website :computer_mouse:

#933 Add a rules document for operators@muc.xmpp.org
  content/pages/community/operators-rules.md
Labels: Board, Website :computer_mouse:
