Repository xsf/xmpp.org, pull requests merged in 2021-05, with the labels that each got.

#918 [newsletter] Update XEP section
  content/posts/newsletter/2021-05-05.md
Labels: Newsletter :email:

#914 REVIEW: XMPP Newsletter April 2021
  content/images/newsletter/2021-04/gajim_chat-view-april.png
  content/images/newsletter/2021-04/yaxim.png
  content/posts/newsletter/2021-05-05.md
Labels: Newsletter :email:

#857 Add a dark variant for the main website
  xmpp.org-theme/static/css/app.css
Labels: Website :computer_mouse:, enhancement

#927 clients: Update 'last_renewed' for Kaidan
  data/clients.json
Labels: Update

#926 Updated XSF Newsletter site formatting and Translation section
  content/pages/newsletter.md
Labels: Website :computer_mouse:

#925 servers.md: Clarify contribution
  content/pages/software/servers.md
Labels: Update, Website :computer_mouse:

#923 clients.md: Clarify contribution
  content/pages/software/clients.md
Labels: Update, Website :computer_mouse:

#928 Renew Gajim and python-nbxmpp
  data/clients.json
  data/libraries.json
Labels: Update

#929 [newsletter] Update XEP section
  content/posts/newsletter/2021-06-05.md
Labels: Newsletter :email:
