Repository xsf/xmpp.org, pull requests merged in 2021-01, with the labels that each got.

#858 Update poezio’s DOAP file.
  data/clients.json
  data/libraries.json
Labels: Update

#859 [newsletter] Added UWPX v.0.30.0.0 news
  content/posts/newsletter/2021-02-05.md
Labels: Newsletter :email:

#860 [newsletter] Add clients, servers, and libraries
  content/posts/newsletter/2021-02-05.md
Labels: Newsletter :email:

#863 DRAFT: [newsletter] Update XEP section
  content/posts/newsletter/2021-02-05.md
Labels: Newsletter :email:

#862 Renew Smack
  data/libraries.json
Labels: Update

#861 Artalk.XMPP
  data/libraries.json
Labels: Update

#867 add blabber.im client
  data/clients.json
Labels: Update

#869 Renew Conversations and add doap file
  data/clients.json
Labels: Update

#872 About: Update Compliance Suites link
  content/pages/about/compliance-suites.md
Labels: Website :computer_mouse:

#873 Renew Psi/Psi+
  data/clients.json
Labels: Update

#871 Add blog article: It is not a choice of the messenger
  content/posts/blog/2021-01-20.md
Labels: Website :computer_mouse:

#870 Update _index.md
  content/pages/getting-started/_index.md
Labels: Website :computer_mouse:

#878 Update 2021-01-24_blog_MessagerieInstantanee-Ilnesagitpasdelapplication
  content/posts/blog/2021-01-24_blog_MessagerieInstantanee-Ilnesagitpasdelapplication
Labels: Website :computer_mouse:

#874 Blog article: German translation "Instant Messaging: It is not a choice of the messenger"
  content/posts/blog/2021-01-24_blog_InstantMessagingEsgehtnichtumdieApp
Labels: Website :computer_mouse:

#879 Blog article: Spanish translation "Instant Messaging: It is not a choice of the messenger"
  content/posts/blog/2021-01-28_blog_MensajeríainstantáneaNosetratadelaaplicación
Labels: Website :computer_mouse:

#875 Blog article: French translation "Instant Messaging: It is not a choice of the messenger"
  content/posts/blog/2021-01-24_blog_MessagerieInstantanee-Ilnesagitpasdelapplication
Labels: Website :computer_mouse:

#876 Blog article: Romanian translation "Instant Messaging: It is not a choice of the messenger"
  content/posts/blog/2021-01-23_MesagerieInstantanee-Nuesteorbadespreaplicatie.md
Labels: Website :computer_mouse:

#877 blog: add metadata to articles
  xmpp.org-theme/templates/article.html
Labels: Website :computer_mouse:

#882 Two stage docker build
  Dockerfile
Labels: Website :computer_mouse:, enhancement
