Repository xsf/xmpp.org, pull requests merged in 2022-12, with the labels that each got.

#1214 Mention the client from scratch article
  content/blog/2022-12-05-newsletter.md
Labels: Newsletter :email:

#1215 Renew Prosody
  data/servers.json
Labels: Update

#1216 Update instant-messaging.md
  content/uses/instant-messaging.md
Labels: Update, Website :computer_mouse:

#1219 New timestamp for Monal stable release with build number 836
  data/clients.json
Labels: Update

#1209 EDITORIAL CLOSING: XMPP Newsletter November 2022
  content/blog/2022-12-05-newsletter.md
  static/images/newsletter/2022-12-05/delete.txt
  static/images/newsletter/2022-12-05/ejabberdturns20.png
  static/images/newsletter/2022-12-05/gajim-file-transfer-interface.png
Labels: Newsletter :email:

#1221 update memberlist Q4-2022 election
  data/members.json
Labels: Update

#1222 Adding IECON2022 paper reference
  data/papers.json
Labels: Update, Website :computer_mouse:

#1226 Update contact.md
  content/about/xmpp-standards-foundation.md
  content/community/chat.md
  content/contact.md
Labels: enhancement, trademark, Website :computer_mouse:, Board, Documentation
