Repository xsf/xmpp.org, pull requests merged in 2022-02, with the labels that each got.

#1065 GSoC2022: Add info to flyers and German translation of the flyer
  content/community/gsoc-2022.de.md
  content/community/gsoc-2022.en.md
  static/images/promo/Flyer_XMPP_GSoC2022_DE.pdf
  static/images/promo/Flyer_XMPP_GSoC2022_EN.png
Labels: enhancement, Website :computer_mouse:

#1066 Add PGPainless 1.0.0 release announcement
  content/blog/newsletter_2022-02-05.md
Labels: Newsletter :email:

#1067 Use a better logo for Linux on the homepage
  static/images/logos/linux.svg
Labels: enhancement, Website :computer_mouse:

#1068 Add canonical link
  themes/xmpp.org/layouts/partials/head.html
Labels: enhancement, Website :computer_mouse:

#1037 EDITORIAL CLOSING: XMPP Newsletter Decemeber 2021 & January 2022
  content/blog/newsletter_2022-02-05.md
  static/images/newsletter/january2022/movim_omemo.png
  static/images/newsletter/january2022/smstoxmpp.png
  static/images/newsletter/january2022/snikket-account-import-export.png
Labels: Newsletter :email:

#1069 Added Spanish translation
  content/blog/newsletter_2022-02-05.es.md
Labels: Newsletter :email:, Localization :flags:

#1073 german translation of the xmpp newsletter
  content/blog/newsletter_2022-02-05.de.md
Labels: Newsletter :email:, Localization :flags:

#1074 Renew poezio & slixmpp data
  data/clients.json
  data/libraries.json
Labels: Update

#1075 Add Renga and Chat-O-Matic clients for Haiku
  data/clients.json
  data/platforms.json
Labels: Update

#1007 Add new sections to myths.md
  content/about/myths.md
Labels: enhancement, Website :computer_mouse:, Board, Documentation

#1079 GSoC ES translation
  content/community/gsoc-2022.es.md
  static/images/promo/Flyer_XMPP_GSoC2022_ES.pdf
Labels: Website :computer_mouse:

#1080 Add Profanity doap
  data/clients.json
Labels: Update

#1082 newsletter.md: Update supported language references
  content/newsletter.md
Labels: Newsletter :email:, Website :computer_mouse:, Localization :flags:
