Repository xsf/xmpp.org, pull requests merged in 2022-01, with the labels that each got.

#1044 Renew all Tigase projects
  data/clients.json
  data/libraries.json
  data/servers.json
Labels: Update

#1045 Add new GSoC 2022 page to xmpp.org/Community
  config/_default/menus.toml
  content/community/gsoc-2022.en.md
  static/images/logos/GSoC_2022_Logo.png
Labels: Website :computer_mouse:

#1056 Renew Libervia
  data/clients.json
Labels: Update

#1046 GSoC2022: Fix error with image and xmpp uri and improve source section
  content/community/gsoc-2022.en.md
Labels: bug, Website :computer_mouse:

#1053 Renew MongooseIM
  data/servers.json
Labels: Update

#1051 Renew JSXC
  data/clients.json
Labels: Update

#1052 Renew Miranda NG
  data/clients.json
Labels: Update

#1057 GSoC 2022: Add German translation
  content/community/gsoc-2022.de.md
Labels: Website :computer_mouse:, Localization :flags:

#1054 Renew QXmpp
  data/libraries.json
Labels: Update

#1058 Update website announcements
  data/announcement.json
Labels: Update, Website :computer_mouse:

#1061 GSoC2022: Add promotion files
  static/images/promo/Flyer_XMPP_GSoC2022_EN.pdf
  static/images/promo/Flyer_XMPP_GSoC2022_EN.png
Labels: Website :computer_mouse:, Documentation

#1062 Update C++ logo
  static/images/logos/cpp.svg
Labels: bug, enhancement, Website :computer_mouse:
