Repository xsf/xmpp.org, pull requests merged in 2023-10, with the labels that each got.

#1305 REVIEW: XMPP Newsletter September 2023
  content/blog/2023-10-05-newsletter.md
  static/images/newsletter/2023-10-05/moxxy-muc-demo.gif
Labels: Newsletter :email:

#1307 Update software _index.md
  content/software/_index.md
Labels: enhancement, Website :computer_mouse:

#1310 Update software.json: CertWatch
  data/software.json
Labels: Update, Website :computer_mouse:

#1315 Erlang/Elixir XMPP library update
  data/software.json
  static/hosted-doap/erlang-elixir-xmpp.doap
Labels: Update
