Repository xsf/xmpp.org, pull requests merged in 2023-01, with the labels that each got.

#1230 Update public server listing links
  content/getting-started.md
Labels: Website :computer_mouse:

#1233 Add slidge DOAP
  data/libraries.json
Labels: Update

#1223 Update gsoc-2022 page and localiation with results
  content/community/gsoc-2022.de.md
  content/community/gsoc-2022.en.md
  content/community/gsoc-2022.es.md
  content/community/gsoc-2022.fr.md
Labels: Website :computer_mouse:, Localization :flags:
