Repository xsf/xmpp.org, pull requests merged in 2024-03, with the labels that each got.

#1350 Update gaming.md
  content/uses/gaming.md
Labels: Update, Website :computer_mouse:, Documentation

#1359 Remove reference to conversations-offtopic-reloaded
  content/community/operators-rules.md
Labels: enhancement, Website :computer_mouse:

#1354 EDITORIAL CLOSING: XMPP Newsletter February 2024
  content/blog/2024-03-10-newsletter.md
  static/images/newsletter/2024-03-05/jmp-sip-gateway.png
Labels: Newsletter :email:

#1360 Erlang Solutions Sponsor
  content/community/sponsors/_index.md
  content/community/sponsors/erlang-solutions.md
  static/images/logos/erlang-solutions.png
  themes/xmpp.org/layouts/partials/footer.html
Labels: Website :computer_mouse:, Board
