Repository xsf/xmpp.org, pull requests merged in 2025-04, with the labels that each got.

#1502 EDITORIAL CLOSING: The XMPP Newsletter March 2025
  content/blog/newsletter/2025-04-05-newsletter.md
Labels: Newsletter :email:

#1511 Update announcement.json for Berlin Sprint
  data/announcement.json
Labels: Website :computer_mouse:

#1513 German translation for the open letter to Meta
  content/announcements/open-letter-meta-dma/technical-briefing.de.md
Labels: Localization :flags:
